### ISSUE TITLE
Set default DEBUG in Dockerfile

### ISSUE THREAD

**Issue by CunliangGeng** [CLARIAH/grlc#281]
The env variable DEBUG does not exist in Dockerfile and uers have to explicitly set it in `docker run` command or docker compose file. If users forget to set it, the DEBUG variable will be a blank value which is then used in `grlc/docker-assets/entrypoint.sh` and leads to the following error:

```
grlc_1      | Reading config file:  /home/grlc/grlc/config.ini
grlc_1      | Traceback (most recent call last):
grlc_1      |   File "/usr/local/bin/grlc-server", line 11, in <module>
grlc_1      |     from grlc.server import app as grlc_app
grlc_1      |   File "/usr/local/lib/python3.6/site-packages/grlc/server.py", line 9, in <module>
grlc_1      |     import grlc.static as static
grlc_1      |   File "/usr/local/lib/python3.6/site-packages/grlc/static.py", line 62, in <module>
grlc_1      |     LOG_DEBUG_MODE = config.getboolean('defaults', 'debug')
grlc_1      |   File "/usr/local/lib/python3.6/configparser.py", line 829, in getboolean
grlc_1      |     raw=raw, vars=vars, fallback=fallback, **kwargs)
grlc_1      |   File "/usr/local/lib/python3.6/configparser.py", line 809, in _get_conv
grlc_1      |     **kwargs)
grlc_1      |   File "/usr/local/lib/python3.6/configparser.py", line 803, in _get
grlc_1      |     return conv(self.get(section, option, **kwargs))
grlc_1      |   File "/usr/local/lib/python3.6/configparser.py", line 1155, in _convert_to_boolean
grlc_1      |     raise ValueError('Not a boolean: %s' % value)
grlc_1      | ValueError: Not a boolean:
grlc_1 exited with code 1
```
 

To avoid this error, it would be nice to set a default DEBUG value in Dockerfile. @c-martinez

**Comment by c-martinez** [comment]
Fixed in v1.3.5
