### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ACCESS_TOKEN'

### ISSUE THREAD

**Issue by barrynl** [CLARIAH/grlc#60]
Hi all,

My GRLC suddenly stopped working with the stack trace below in the GRLC logs. It requires an ACCESS_TOKEN and I've located the config.ini file that contains the following content:

[auth]
github_access_token =

Apparently, I need to give a github_access_token, but I do not know how to get one. I also wonder why public access requires an Access Token on github.

Regards, Barry

```
[2017-06-09 13:09:45 +0000] [177] [INFO] Booting worker with pid: 177
2017-06-09 13:39:04,773 [INFO] (server.swagger_spec) -----> Generating swagger spec for ... on commit None
2017-06-09 13:39:06,349 [DEBUG] (prov.init_prov_graph) Ingesting Git2PROV output into RDF graph
2017-06-09 13:39:06,441 [ERROR] (app.log_exception) Exception on /api/.../.../spec [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/grlc/grlc/src/server.py", line 190, in swagger_spec
    swag = utils.build_swagger_spec(user, repo, sha, static.SERVER_NAME, prov_g)
  File "/home/grlc/grlc/src/utils.py", line 242, in build_swagger_spec
    resp = requests.get(api_repo_uri, headers={'Authorization': 'token {}'.format(static.ACCESS_TOKEN)}).json()
AttributeError: 'module' object has no attribute 'ACCESS_TOKEN'
```

**Comment by barrynl** [comment]
Hi all,

I thought I found the solution, but unfortunately, it did not work:
- Generated a 'Personal Access Token' in my Github settings.
- Modified the docker-compose.yml I was using with the variable:

`    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
     - GRLC_GITHUB_ACCESS_TOKEN=...personal...access...token...`

But the error above remains...also on github repositories that I did not create myself. Maybe I should not use the 'Personal Access Token'??

Regards, Barry

**Comment by barrynl** [comment]
Hi, solved this issue.

I use GRLC in my docker-compose application where I am using a custom static.py with my default endpoint, etc. However, the static.py changed to include the ACCESS_TOKEN attribute, but it was being replaced by my older version of static.py (docker-compose build). So, it did not contain any ACCESS_TOKEN attribute (as the error says). I've updated my custom static.py to the latest version and now it works.

Regards, Barry
